### ISSUE TITLE
🐳 Jobs von APIs entkoppeln

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1276]
## democracy api

- [x] sync from bio – procedures
- [x] sync from bio – named polls
- [x] sync from bio – deputy profiles
- [x] sync from bio – resync all

## democracy api

- [x] import procedures
- [x] conference week details
- [x] import named polls
- [x] import named polls deputy profiles
- [x] import deputy profiles
