### ISSUE TITLE
📱 [Design 1.4] DetailPage nach Abstimmung

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1363]
Dieses Ticket beschäftigt sich mit der Evaluation der DetailPage nach Abstimmung im derzeitigen 1.4-Design (Internal Version 1.4.0 (12))

### COMMUNITY (bundesweit)
- [ ]  Beschriftung "Bundesweit" wieder in "Deutschland" zurückändern
- [ ] Deutschland-Icon verkleinern und in SecondaryColor grau
- [ ]  Fontgröße für % und "25 Abstimmende" anpassen
- [ ]  PieChart-Größe minimal verkleinen
- [ ]  Abstände zwischen Legende und Swipe-Punkten vergrößern
- [ ]  "Dieses Ergebnis wurde nicht auf seine Repräsentativität geprüft." wie in 1.3.9 nach seine brechen
- [ ]  Teilen-Symbol im lilanen Kreis zentrieren
- [ ]  für die Abstände zum Rand links/rechts gilt das gleiche wie in #1360 und #1361

![CommunityGer](https://user-images.githubusercontent.com/32302889/109133941-ccfd2600-7755-11eb-804f-416044de7e43.png)

### COMMUNITY (WK)
- [ ]  Die Darstellung wieder auf das PieChart beschränken; die Karte im Code auskommentieren. Dafür besteht noch kein ausgereiftes Konzept. Eine komplette Deutschlandkarte anzuzeigen, erscheint mir wenig sinnvoll. Es braucht an dieser Stelle entweder eine WK-Suche oder man stellt vorher Favoriten-WK ein. An dieser Stelle für 1.4 zu aufwendig.
- [ ] alle Designanwendungen für das PieChart (WK-Name, WK-Symbol, Legende,... wie oben in 1.-5.)

![CommunityWK](https://user-images.githubusercontent.com/32302889/109134334-35e49e00-7756-11eb-9526-35467b3ab9d4.png)

### BUNDESTAG (Pie)

- [ ]  Fontgröße für % und "25 Abstimmende" anpassen
- [ ]  PieChart-Größe minimal verkleinen
- [ ]  Abstände zwischen Legende und Swipe-Punkten passen hier!
- [ ]  für die Abstände zum Rand links/rechts gilt das gleiche wie in #1360 und #1361

![BTPie](https://user-images.githubusercontent.com/32302889/109135091-fd918f80-7756-11eb-8ed2-686a6f8195f7.png)

### BUNDESTAG (Bar)
- [ ] einfach nur geil, für Farbschema siehe #684
- [ ]  Abstände zwischen Legende und Swipe-Punkten passen hier auch!

![BTBar](https://user-images.githubusercontent.com/32302889/109135348-40ebfe00-7757-11eb-9b86-bdb6e12d3901.png)

### BUNDESTAG (Party)
- [ ]  ebenfalls super, für Farbschema siehe #684

![BTParty](https://user-images.githubusercontent.com/32302889/109135602-89a3b700-7757-11eb-934e-65a9999b735b.png)

### BUNDESTAG (Kandidat)
- [ ] Obwohl ich den WK eingestellt habe, fehlt diese Darstellung komplett - bitte nachliefern und bedenken, dass wir in Zukunft die Abgeordnetenergebnisse in einem eigenen Reiter anzeigen, vgl. #1162 unter "Abgeordnetenergebnis"

![BTKandidat](https://user-images.githubusercontent.com/32302889/109135774-b788fb80-7757-11eb-98a0-671cd27371da.png)
