### ISSUE TITLE
📱 [Design 1.4] Suche

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1364]
Dieses Ticket beschäftigt sich mit der Evaluation der Suche im derzeitigen 1.4-Design (Internal Version 1.4.0 (12))

- [ ] Abstände in der Vorschlagsliste Zuletzt Gesucht / Meistgesucht stimmen nicht, vgl. Screenshot 1
- [ ]  Der Separater im DarkTheme ist blau und muss gemäß #684 in #777777, vgl. Screenshot 1
- [ ]  Der Ergebnisseperator muss gemäß #684 ebenfalls in #777777, vgl. Screenshot 2
- [ ]  Die Suchtreffer sollen wie im ListView angezeigt werden, vgl. #1360, vgl. Screenshot 2

![Suche1](https://user-images.githubusercontent.com/32302889/109143721-a1336d80-7760-11eb-8973-a43897329035.png)
![Suche2](https://user-images.githubusercontent.com/32302889/109143727-a42e5e00-7760-11eb-8676-fa0bcf3edf55.png)
