### ISSUE TITLE
📱[Design 1.4] WOM

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1366]
Dieses Ticket beschäftigt sich mit der Evaluation des Wahl-O-Meters im derzeitigen 1.4-Design (Internal Version 1.4.0 (12))

### BT-WOM

- [ ]  für die Abstände zum Rand links/rechts gilt das gleiche wie in #1360
- [ ]  PieChart-Größe Community/BT-Chart anpassen
- [ ]  Fontgröße für % und "Bundestag Wahl-O-Meter" anpassen
- [ ]  % sind über 100% - Fehler - bitte Berechnung korrigieren!
- [ ]  DarkTheme: Der beschreibende Text " Höhe Übereinstimmungen Ihrer Stellungnahmen..." ist schwer zu lesen -> Sec. Text Color #B5B5B5
- [ ] es fehlt der Separator mit Abstimmungen (in DarkMode in #777777) komplett, BITTE BEACHTEN, dass in Zukunft auch hier Sitzungswochenseperatoren gezeigt werden, vgl. #953
- [ ] die Abstimmungsliste darunter wie in #1360 

![WOM1](https://user-images.githubusercontent.com/32302889/109145847-5830e880-7763-11eb-9ba2-4d131d74dd22.png)

### Party-WOM

- [ ]  für die Abstände zum Rand links/rechts gilt das gleiche wie in #1360
- [ ]  das Chart finde ich super, in dieser Ansicht würde ich allerdings die %-Zahlen aller Parteien (wenn auch unhighlighted im farbloseren Stil) anzeigen
- [ ]  wie oben DarkTheme: Der beschreibende Text " Höhe Übereinstimmungen Ihrer Stellungnahmen..." ist schwer zu lesen -> Sec. Text Color #B5B5B5
- [ ]  es fehlt der Separator mit Abstimmungen (in DarkMode in #777777) komplett, BITTE BEACHTEN, dass in Zukunft auch hier Sitzungswochenseperatoren gezeigt werden, vgl. #953
- [ ]  wie oben die Abstimmungsliste darunter wie in #1360 

![WOM2](https://user-images.githubusercontent.com/32302889/109146335-fe7cee00-7763-11eb-998d-3f9d9f409528.png)

### WK-WOM

BITTE BEACHTEN, dass diese Ansicht in Zukunft so nicht mehr existiert, vgl. #953

- [ ]  für die Abstände zum Rand links/rechts gilt das gleiche wie in #1360
- [ ]  Warum ist die "23/144" Anzeige nur in diesem WOM/Wahlkreis tiefer? -> bitte anpassen
- [ ]  DarkTheme: "Thomas Oppermann" [Name] in weiß #FFFFFF
- [ ]  Übereinstimmungsbalken in der Breite verkleinern (Abstände!) und in der Höhe wie bei WOM/Fraktionen
- [ ]  wie oben DarkTheme: Der beschreibende Text " Höhe Übereinstimmungen Ihrer Stellungnahmen..." ist schwer zu lesen -> Sec. Text Color #B5B5B5
- [ ]  wie oben es fehlt der Separator mit Abstimmungen (in DarkMode in #777777) komplett
- [ ]  wie oben die Abstimmungsliste darunter wie in #1360 

![WOM3](https://user-images.githubusercontent.com/32302889/109146895-ab576b00-7764-11eb-8a4e-23b2900930f8.png)
