### ISSUE TITLE
📱[Design 1.4] Abgeordnetenprofil

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1367]
Dieses Ticket beschäftigt sich mit der Evaluation der Abgeordnetenseite im derzeitigen 1.4-Design (Internal Version 1.4.0 (12))

BITTE BEACHTEN, dass diese Seite gem.#1162 in Zukunft zusätzlich die Kandidatenübereinstimmung sowie die KW-Abstimmungsliste enthalten wird (vgl. dazu den letzten Kommentar in #1162)

- [ ] für die Abstände zum Rand links/rechts gilt das gleiche wie in #1360, vgl. v.a. Screenshot 2
- [ ] Farbcodes für DarkTheme aus #684 verwenden
- [ ] DarkTheme: "Thomas Oppermann" [Name] in weiß #FFFFFF
- [ ] Anzahl teilgenommen Abstimmungen 72% in weiß #FFFFFF
- [ ] Dropdown-Abstände (Biographie, Kontakt) anpassen an 1.3.9 und wie in #1361 5. 
- [ ] Text (Biographie usw.) in weiß #FFFFFF, vgl. v.a. Screenshot 2
- [ ] Kontaktmöglichkeiten fehlen in 1.4 komplett - bitte nacharbeiten! 

![Abgeordnete1](https://user-images.githubusercontent.com/32302889/109148411-87952480-7766-11eb-9efa-bd2011d32bda.png)
![Abgeordnete2](https://user-images.githubusercontent.com/32302889/109148415-89f77e80-7766-11eb-8a32-6af62a8ffe5f.png)
