### ISSUE TITLE
📱[Design 1.4] Verifizieren

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1372]
Dieses Ticket beschäftigt sich mit der Evaluation des Verifikationsprozesses im derzeitigen 1.4-Design (Internal Version 1.4.0 (12)) im Vergleich zur 1.3.9 (in diesem Fall getestet auf einem iPhone 6s)

### SideMenu
- [ ] SideMenu "Verifizieren" in "unverifizierter Nutzer" umbenennen (vgl. 1.3.9)
- [ ] daneben im 'Unverifizierten Zustand (ohne Wahlkreis)' anstatt der DEMOCRACY-Bubble aus 1.3.9 bitte das iOS-App-Logo in vergleichbarer Größe

![Verifizieren1](https://user-images.githubusercontent.com/32302889/110103215-f9442280-7da5-11eb-9fac-79afc0a6df68.png)

### VerifizierenÜbersicht
- [ ] es fehlt die Möglichkeit, zurückzunavigieren und die Verifikation zu verlassen!
- [ ] Farben gemäß #684 
- [ ] Abstände nach links und rechts gemäß #1360 2.
- [ ] Padding der 'DEMOCRACY Bubble' zum oberen Rand erhöhen
- [ ] DEMOCRACY Bubble durch iOS-App-Logo ersetzen
- [ ] Die Links im Text hinterlegen

![Verifizieren2](https://user-images.githubusercontent.com/32302889/110104101-031a5580-7da7-11eb-8aa5-6916b2f2ac48.png)

### TelNrEingabe
- [ ] Farben gemäß #684 
- [ ] Abstände nach links und rechts gemäß #1360 2. (hier v.a. Button)
- [ ] Padding der 'DEMOCRACY Bubble' zum oberen Rand erhöhen
- [ ] DEMOCRACY Bubble durch iOS-App-Logo ersetzen

![Verifizieren3](https://user-images.githubusercontent.com/32302889/110104223-2a712280-7da7-11eb-9762-74ee28a6e8f2.png)

### TelNrBestätigung
super

![Verifizieren4](https://user-images.githubusercontent.com/32302889/110104269-3826a800-7da7-11eb-9c10-859a2b6e1333.png)

### CodeEingabe
- [ ] Farben gemäß #684, hier v.a. SMSCode-Text in weiß #FFFFFF
- [ ] Abstände nach links und rechts gemäß #1360 2. (hier v.a. Button)
- [ ] Padding der 'DEMOCRACY Bubble' zum oberen Rand erhöhen
- [ ] DEMOCRACY Bubble durch iOS-App-Logo ersetzen

![Verifizieren5](https://user-images.githubusercontent.com/32302889/110104936-0feb7900-7da8-11eb-85af-25402ee60e62.png)

### VerificationSuccess
Padding der 'DEMOCRACY Bubble' zum oberen Rand ist super!
- [ ] Farben gemäß #684, hier v.a. Secondary Text heller 
- [ ] Das ist der einzige Screen, wo wir eine Customized Font (Helvetica Neue Light) haben; bitte durch Systemfont ersetzen

![Verifizieren6](https://user-images.githubusercontent.com/32302889/110104841-f34f4100-7da7-11eb-8108-d768d754f3c2.png)
