### ISSUE TITLE
📱[Design 1.4] Rechtliches

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1381]
Dieses Ticket beschäftigt sich mit der Evaluation des Rechtliches im derzeitigen 1.4-Design (Internal Version 1.4.0 (12)) im Vergleich zur 1.3.9

- [ ] Abstände links und rechts vergrößern vgl. #1360 
- [ ] Layerhöhe (Impressum,...) an 1.3.9 anpassen = vergrößern
- [ ] Schriftfarben gemäß #684 anpassen
- [ ] KontaktIcons weiß 
- [ ] "Made with Heart" unten in weiß oder auf grauem #777777 Hintergrund absetzen, vgl. #1379

![Rechtliches](https://user-images.githubusercontent.com/32302889/110124369-48984c00-7dc2-11eb-98ab-8f5c58a7ebae.png)
