### ISSUE TITLE
📱[Design 1.4] Spenden

### ISSUE THREAD

**Issue by visionmakery** [demokratie-live/democracy-client#1382]
Dieses Ticket beschäftigt sich mit der Evaluation des Spenden im derzeitigen 1.4-Design (Internal Version 1.4.0 (12)) im Vergleich zur 1.3.9

- [ ] Abstände links und rechts der einzelnen Donate-Balken anpassen
- [ ] Schriftfarben gemäß #684 anpassen, hier v.a. Zahlen und Text weiß
- [ ] Seperatorfarbe #777777, Seperatortext gem. @684
- [ ] Untertitel in den einzelnen Donatebalken fehlen komplett - nachtragen!
- [ ] "Made with Heart" unten in weiß oder auf grauem #777777 Hintergrund absetzen, vgl. #1379

![Donate](https://user-images.githubusercontent.com/32302889/110125036-281cc180-7dc3-11eb-9300-ff1b09111dfd.png)
