### ISSUE TITLE
📱 Deputy Search

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#1450]
[Zeplin](https://zpl.io/aNO0rMN)

![Bildschirmfoto 2021-04-09 um 13 56 06](https://user-images.githubusercontent.com/32302889/114176433-6ade3600-993b-11eb-9947-77fd3be731ed.png)

# ToDo's
- [x] Create new ScreenStack in SidebarStack
- [x] Create DeputySearch Screen
- [x] create GraphQL query to get list of deputies
  - [x] Multiquery
    1.  [x] get Favorized deputies
    2. [x] get last name sorted deputies (exclude deputies from first query)
  - All with filter by
    - [x] name
    - [ ] party
    - [x] constituency
    - [ ] plz
    - [ ] city
- [x] create favourite deputies store handler
  - [ ] ❓ Apollo Local Storage Persist
  - [x] ❓ AsyncStorage ⭐️
- [x] Create State Handler for **Search**, **Query Handling** and Edit Mode
  - [x] DeputyList Query & Data <- Search
  - [x] Search input handling -> Query
  - [x] Edit Mode
    - [x] Switcher
    - [ ] change deputy favourites
      - [ ] reorder
      - [x] add
      - [x] remove
- [x] Add SearchComponent
- [x] Add DeputyList Component
- [x] Add Edit Button in Top Right Header ( Toggle to Fertig if enabled)
